In [1]:
l = range(1000000) 

In [33]:
import numpy as np #importing numpy and using np as alais

In [3]:
d = np.arange(1000000) #creating a range of numbers

In [4]:
%time for i in range(10): x = [x*2 for x in l] #calculation time and comparing with normal python lists

Wall time: 1.12 s


In [5]:
%time for i in range(10): d*2 #time complexity of normal python lists

Wall time: 31.2 ms


In [6]:
x = np.zeros((4,4)) #creating a 4 by 4 matrix of zeros

In [7]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
x1 = np.ones((4,4)) #creating a 4 by 4 matric of ones

In [9]:
x1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
x2 = np.empty((7,7)) #Return a new array of given shape and type, without initializing entries.


1.Parameters

    1.1. shapeint or tuple of int

       1.1.1. Shape of the empty array, e.g., (2, 3) or 2.
    1.2. dtypedata-type, optional

        1.2.1. Desired output data-type for the array, e.g, numpy.int8. Default is numpy.float64.
    1.3. order{‘C’, ‘F’}, optional, default: ‘C’

        1.3.1. Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order in memory.

2.Returns

    2.1. outndarray

        2.2. Array of uninitialized (arbitrary) data of the given shape, dtype, and order. Object arrays will be initialized to None.



In [11]:
x2

array([[1.13815421e-311, 1.13813731e-311, 1.13815798e-311,
        1.13815798e-311, 1.13815798e-311, 1.13815798e-311,
        1.13815798e-311],
       [1.13815798e-311, 1.13815798e-311, 1.13815798e-311,
        1.13815798e-311, 1.13815798e-311, 1.13815798e-311,
        1.13815798e-311],
       [1.13815798e-311, 1.13815798e-311, 1.13815798e-311,
        1.13815798e-311, 1.13815798e-311, 1.13815798e-311,
        1.13815798e-311],
       [1.13815798e-311, 1.13815798e-311, 1.13815798e-311,
        1.13815798e-311, 1.13815798e-311, 1.13815798e-311,
        1.13815790e-311],
       [1.13815790e-311, 1.13815798e-311, 1.13815798e-311,
        1.13815798e-311, 1.13815798e-311, 1.13815790e-311,
        1.13815790e-311],
       [1.13815790e-311, 1.13815790e-311, 1.13815790e-311,
        1.13815790e-311, 1.13815798e-311, 1.13815798e-311,
        1.13815798e-311],
       [1.13815798e-311, 1.13815798e-311, 1.13815798e-311,
        1.13815798e-311, 1.13815798e-311, 1.13815798e-311,
        1.13815798

In [14]:
x3 = np.arange(1,100,10) 

1. Return evenly spaced values within a given interval.

2. Values are generated within the half-open interval [start, stop) (in other words, the interval including start but excluding stop). For integer arguments the function is equivalent to the Python built-in range function, but returns an ndarray rather than a list.

3. When using a non-integer step, such as 0.1, the results will often not be consistent. It is better to use numpy.linspace for these cases.


1. Parameters

    1.1. startnumber, optional

        1.1.1. Start of interval. The interval includes this value. The default start value is 0.
    1.2. stopnumber

        1.2.1. End of interval. The interval does not include this value, except in some cases where step is not an integer and floating point round-off affects the length of out.
    1.3. stepnumber, optional

        1.3.1. Spacing between values. For any output out, this is the distance between two adjacent values, out[i+1] - out[i]. The default step size is 1. If step is specified as a position argument, start must also be given.
    1.4. dtypedtype

        1.4.1. The type of the output array. If dtype is not given, infer the data type from the other input arguments.

2. Returns

    2.1. arangendarray

        2.1.1.  Array of evenly spaced values.

        2.1.2. For floating point arguments, the length of the result is ceil((stop - start)/step). Because of floating point overflow, this rule may result in the last element of out being greater than stop.



In [15]:
x3

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [16]:
x3.shape # return the shape of the matric in the form of the tuple

(10,)

In [21]:
x4 = np.zeros((10,6))

In [22]:
x4

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
when you want to reshape the number of elements should remain the same.

In [23]:
x4.shape 

(10, 6)

In [ ]:
#The example above returns (10, 6), which means that the array has 10 dimensions, and each dimension has 6 elements.

In [26]:
x = x4.reshape(20,3)

 1. numpy.reshape(a, newshape, order='C')[source]

    1.1. Gives a new shape to an array without changing its data.

    1.2. Parameters

        1. aarray_like

            1.1. Array to be reshaped.
        2. newshapeint or tuple of ints

            2.1. The new shape should be compatible with the original shape. If an integer, then the result will be a 1-D array of that length. One shape dimension can be -1. In this case, the value is inferred from the length of the array and remaining dimensions.
        3. order{‘C’, ‘F’, ‘A’}, optional

            3.1. Read the elements of a using this index order, and place the elements into the reshaped array using this index order. ‘C’ means to read / write the elements using C-like index order, with the last axis index changing fastest, back to the first axis index changing slowest. ‘F’ means to read / write the elements using Fortran-like index order, with the first index changing fastest, and the last index changing slowest. Note that the ‘C’ and ‘F’ options take no account of the memory layout of the underlying array, and only refer to the order of indexing. ‘A’ means to read / write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise.

    1.3. Returns

        1. reshaped_arrayndarray

            1.1. This will be a new view object if possible; otherwise, it will be a copy. Note there is no guarantee of the memory layout (C- or Fortran- contiguous) of the returned array.



In [27]:
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
x.shape

(20, 3)

In [30]:
x = x.reshape(60,1)

In [31]:
x

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [32]:
x.shape

(60, 1)

In [34]:
a = np.random.randn((10))
b = np.random.randn((10))

1. Return a sample (or samples) from the “standard normal” distribution.

2. If positive, int_like or int-convertible arguments are provided, randn generates an array of shape (d0, d1, ..., dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1 (if any of the d_i are floats, they are first converted to integers by truncation). A single float randomly sampled from the distribution is returned if no argument is provided.

3. This is a convenience function. If you want an interface that takes a tuple as the first argument, use 

In [35]:
a

array([-0.23780186, -1.63938115,  0.41394069, -0.79549362,  0.25046646,
       -0.06089542,  1.19451838, -0.9338649 ,  1.20040032,  0.95102002])

In [36]:
b

array([ 0.17072384,  1.36407116,  0.86530418, -1.85776542, -0.67969963,
       -0.7600406 , -0.66169138, -1.59755971, -1.75210278,  0.53703372])

In [37]:
a+b

array([-0.06707802, -0.27530999,  1.27924487, -2.65325904, -0.42923317,
       -0.82093602,  0.532827  , -2.53142461, -0.55170246,  1.48805373])

In [38]:
a*b 

array([-0.04059845, -2.23623254,  0.35818461,  1.47784054, -0.17024196,
        0.04628299, -0.79040252,  1.49190494, -2.10322474,  0.51072982])

In [39]:
a*2

array([-0.47560373, -3.2787623 ,  0.82788138, -1.59098724,  0.50093292,
       -0.12179084,  2.38903676, -1.86772981,  2.40080064,  1.90204003])

In [40]:
a/2

array([-0.11890093, -0.81969057,  0.20697035, -0.39774681,  0.12523323,
       -0.03044771,  0.59725919, -0.46693245,  0.60020016,  0.47551001])

In [41]:
a>0

array([False, False,  True, False,  True, False,  True, False,  True,
        True])

In [42]:
a<0

array([ True,  True, False,  True, False,  True, False,  True, False,
       False])

In [43]:
a[a>0]

array([0.41394069, 0.25046646, 1.19451838, 1.20040032, 0.95102002])

In [44]:
a[[1,3,5,7]]

array([-1.63938115, -0.79549362, -0.06089542, -0.9338649 ])

In [45]:
a[1:10:-1]

array([], dtype=float64)

In [46]:
a[1:10:1]

array([-1.63938115,  0.41394069, -0.79549362,  0.25046646, -0.06089542,
        1.19451838, -0.9338649 ,  1.20040032,  0.95102002])

In [48]:
x = np.random.randn(10,10)

In [49]:
x

array([[-2.41706885e+00,  5.63138357e-01,  7.71651060e-01,
        -3.71688628e-01,  4.38249750e-01,  1.27045590e+00,
         4.25645945e-01,  3.19376994e+00, -5.26733770e-01,
        -2.31063739e-01],
       [ 1.20223955e+00,  1.12211518e+00,  3.70958783e-01,
        -4.02617372e-01, -5.61548248e-01, -1.15557134e+00,
         5.97192311e-01,  9.63434212e-01,  1.27145514e-01,
         1.91951444e+00],
       [ 6.87668873e-01,  4.82738299e-01,  4.67171031e-01,
        -8.26081033e-02, -4.65738166e-03, -7.12219818e-01,
        -8.80145117e-01,  3.58207479e-01,  1.62563049e+00,
         1.48652668e-01],
       [ 2.66153302e+00, -7.89572806e-01,  1.40151999e+00,
         4.25593360e-01,  9.37763604e-01,  8.57690962e-02,
         3.25856840e-01, -3.08451589e-01, -8.41732792e-01,
        -2.25499433e-01],
       [-4.02509848e-02, -2.42530246e-01, -1.26611300e-01,
        -2.32895578e-03,  4.79361279e-01,  1.43164303e+00,
        -4.54521345e-01,  1.42397160e+00,  6.72229053e-01,
         2.

In [50]:
x[1]

array([ 1.20223955,  1.12211518,  0.37095878, -0.40261737, -0.56154825,
       -1.15557134,  0.59719231,  0.96343421,  0.12714551,  1.91951444])

In [51]:
x[1][4]

-0.5615482475043837

In [53]:
x[0:10:2]

array([[-2.41706885e+00,  5.63138357e-01,  7.71651060e-01,
        -3.71688628e-01,  4.38249750e-01,  1.27045590e+00,
         4.25645945e-01,  3.19376994e+00, -5.26733770e-01,
        -2.31063739e-01],
       [ 6.87668873e-01,  4.82738299e-01,  4.67171031e-01,
        -8.26081033e-02, -4.65738166e-03, -7.12219818e-01,
        -8.80145117e-01,  3.58207479e-01,  1.62563049e+00,
         1.48652668e-01],
       [-4.02509848e-02, -2.42530246e-01, -1.26611300e-01,
        -2.32895578e-03,  4.79361279e-01,  1.43164303e+00,
        -4.54521345e-01,  1.42397160e+00,  6.72229053e-01,
         2.58864522e-01],
       [ 1.01212664e+00,  8.32482768e-01, -4.26037551e-01,
        -1.10281365e+00, -1.76123403e-01, -1.96742431e+00,
         1.88902444e+00, -8.08678967e-01, -4.57697927e-02,
         2.16258219e+00],
       [ 2.05051331e+00, -8.91024794e-01, -4.70316498e-02,
         1.83920797e+00, -1.53664786e-01, -2.44371469e-02,
        -9.16448252e-01, -4.31966802e-01,  5.57105047e-01,
         9.

In [54]:
x[::,0:4]

array([[-2.41706885e+00,  5.63138357e-01,  7.71651060e-01,
        -3.71688628e-01],
       [ 1.20223955e+00,  1.12211518e+00,  3.70958783e-01,
        -4.02617372e-01],
       [ 6.87668873e-01,  4.82738299e-01,  4.67171031e-01,
        -8.26081033e-02],
       [ 2.66153302e+00, -7.89572806e-01,  1.40151999e+00,
         4.25593360e-01],
       [-4.02509848e-02, -2.42530246e-01, -1.26611300e-01,
        -2.32895578e-03],
       [ 1.75794575e+00,  2.10404806e+00, -4.86712385e-01,
         4.05547051e-01],
       [ 1.01212664e+00,  8.32482768e-01, -4.26037551e-01,
        -1.10281365e+00],
       [-2.92534229e-01, -8.46627418e-01,  3.36248516e-01,
        -8.94620823e-01],
       [ 2.05051331e+00, -8.91024794e-01, -4.70316498e-02,
         1.83920797e+00],
       [ 1.81772722e+00, -8.30145067e-01, -5.78613145e-01,
         6.86304985e-01]])

In [63]:
ones = np.ones((4,4))

In [64]:
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [60]:
ones[1:-1,1:-1]=0

In [61]:
ones

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [71]:
ones[0:4:2]=1

In [72]:
ones

array([[1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [0., 0., 0., 0.]])

In [1]:
import numpy as np
np.random.seed(1)

In [ ]:
#With the seed reset (every time), the same set of numbers will appear every time.

In [2]:
np.random.randn(5,5)* 0.01

array([[ 0.01624345, -0.00611756, -0.00528172, -0.01072969,  0.00865408],
       [-0.02301539,  0.01744812, -0.00761207,  0.00319039, -0.0024937 ],
       [ 0.01462108, -0.02060141, -0.00322417, -0.00384054,  0.01133769],
       [-0.01099891, -0.00172428, -0.00877858,  0.00042214,  0.00582815],
       [-0.01100619,  0.01144724,  0.00901591,  0.00502494,  0.00900856]])

In [3]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])