In [2]:
import numpy as np

In [3]:
array= np.arange(1000000)
%time array2= array*2

Wall time: 4 ms


In [5]:
list1= range(1000000)
%time list2= [x*2 for x in list1]

Wall time: 133 ms


In [10]:
random_numbers= np.random.randn(2,3)
random_integers= np.random.randint(low=0, high=1000)

In [11]:
random_integers

764

In [13]:
random_numbers

array([[ 1.07399834, -0.52458996, -1.31149992],
       [ 2.75222289,  0.1252626 ,  0.67018506]])

In [15]:
random_numbers* 5.

array([[ 5.3699917 , -2.6229498 , -6.55749961],
       [13.76111444,  0.626313  ,  3.35092528]])

In [17]:
random_numbers.shape

(2, 3)

In [20]:
random_numbers.flatten()

array([ 1.07399834, -0.52458996, -1.31149992,  2.75222289,  0.1252626 ,
        0.67018506])

In [22]:
random_numbers.ravel()

array([ 1.07399834, -0.52458996, -1.31149992,  2.75222289,  0.1252626 ,
        0.67018506])

In [24]:
random_numbers.dtype

dtype('float64')

In [25]:
random_numbers.astype('int64')

array([[ 1,  0, -1],
       [ 2,  0,  0]], dtype=int64)

In [26]:
li= [[1,2,3,4,5],[[1,2,3,4,5],[1,2,3,4,5]],[3,4,5,6,1]]

In [30]:
array1= np.array(li)
array1.dtype

dtype('O')

In [31]:
array1.shape

(3,)

In [32]:
array1.ndim

1

In [33]:
data= np.zeros(10, dtype='int32')

In [34]:
data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
import random
random.seed(0)

In [31]:
random.seed(0)
arr= np.random.randn(5,2)
arr

array([[-0.78170988, -0.37793392],
       [ 0.97550198, -0.86899216],
       [ 1.02738498, -1.33851932],
       [-1.20887436,  1.02953283],
       [-0.1855659 , -0.65278255]])

In [36]:
first, second, third, = np.split(arr, [1,3])
first

array([[-0.78170988, -0.37793392]])

In [33]:
second

array([[ 0.97550198, -0.86899216],
       [ 1.02738498, -1.33851932]])

In [34]:
third

array([[-1.20887436,  1.02953283],
       [-0.1855659 , -0.65278255]])

In [44]:
x= np.random.randn(4,4)

In [45]:
x

array([[ 0.66838574,  0.3241437 ,  0.6274845 ,  0.36667655],
       [-0.47722998,  0.92594268, -0.42195953, -0.90728748],
       [-0.35971945, -0.78988106,  0.35936242, -0.73280672],
       [ 0.09998107, -0.55593401, -0.05054866, -0.48755949]])

In [49]:
np.vsplit(x, 1)

[array([[ 0.66838574,  0.3241437 ,  0.6274845 ,  0.36667655],
        [-0.47722998,  0.92594268, -0.42195953, -0.90728748],
        [-0.35971945, -0.78988106,  0.35936242, -0.73280672],
        [ 0.09998107, -0.55593401, -0.05054866, -0.48755949]])]

In [51]:
np.hsplit(x, 2)

[array([[ 0.66838574,  0.3241437 ,  0.6274845 ,  0.36667655],
        [-0.47722998,  0.92594268, -0.42195953, -0.90728748],
        [-0.35971945, -0.78988106,  0.35936242, -0.73280672],
        [ 0.09998107, -0.55593401, -0.05054866, -0.48755949]])]

In [52]:
xa= np.arange(16).reshape(4,4)

In [54]:
xa

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
np.hsplit(xa, range(1,4))[1]

array([[ 1],
       [ 5],
       [ 9],
       [13]])

In [67]:
arr1= np.arange(6).reshape(2,3)
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [72]:
arr2= np.arange(6,12).reshape(2,3)
arr2

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [73]:
np.r_[arr1, arr2]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [78]:
np.hstack((arr1, arr2))

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [76]:
np.c_[arr1, arr2]

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [77]:
np.vstack((arr1,arr2))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [79]:
arr = np.random.randn(2, 2)
arr

array([[ 0.35442339, -1.45757225],
       [ 0.16241986, -0.45847758]])

In [81]:
arr.repeat([2,3], axis=1)

array([[ 0.35442339,  0.35442339, -1.45757225, -1.45757225, -1.45757225],
       [ 0.16241986,  0.16241986, -0.45847758, -0.45847758, -0.45847758]])